name: 'security-netlify-trivy'
description: 'python wrapped trivy report parser adding features like suppression handling'
inputs:
  trivy_report_file_path:
    description: 'location of trivy report that will be parsed'
    required: true
    default: 'trivy_report.json'
  suppression_file_path:  # id of input
    description: 'path/name of suppression list file'
    required: false
    default: 'suppressions-trivy'
  create_github_issue:
    description: 'boolean if user wishes to create github issues'
    required: false
    default: 'false'
  github_min_severity:
    description: 'issues will be created for all discovered vulnerabilities with >= this severity'
    required: false
    default: ''
  create_slack_notification:
    description: 'boolean if user wishes to create slack alert'
    required: false
    default: false
  slack_min_severity:
    description: 'alerts will be sent to slack for all discovered vulnerabilities with >= severity'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.suppression_file_path }}
    - ${{ inputs.trivy_report_file_path }}
    - ${{ inputs.create_github_issue }}
    - ${{ inputs.github_min_severity }}
    - ${{ inputs.create_slack_notification }}
    - ${{ inputs.slack_min_severity }}
  env:
    - CONTAINER_SCAN_SLACK_WEBHOOK: ${{ secrets.CONTAINER_SCAN_SLACK_WEBHOOK }}
    - CONTAINER_SCAN_GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - GITHUB_REPO: ${{ github.repository}}
branding:
  icon: 'life-buoy'
  color 'white'
